name: Create Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            bin_name: nimble-linux
            archive_name: nimble-linux.tar.gz
          - os: macos-latest
            bin_name: nimble-macos
            archive_name: nimble-macos.tar.gz

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up C++ environment on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y clang make

      - name: Set up C++ environment on macOS
        if: matrix.os == 'macos-latest'
        run: xcode-select --install || true

      - name: Build the project
        run: make compile

      - name: Rename binary
        run: mv bin/nimble ${{ matrix.bin_name }}
        shell: bash

      - name: Archive binary
        run: tar -czvf ${{ matrix.archive_name }} ${{ matrix.bin_name }}
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.archive_name }}
          path: ${{ matrix.archive_name }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: nimble-linux.tar.gz
          path: .
      - uses: actions/download-artifact@v3
        with:
          name: nimble-macos.tar.gz
          path: .

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            NIMBLE release. Version ${{ github.ref }}.
          draft: false
          prerelease: false

      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nimble-linux.tar.gz
          asset_name: nimble-linux.tar.gz
          asset_content_type: application/gzip

      - name: Upload macOS binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nimble-macos.tar.gz
          asset_name: nimble-macos.tar.gz
          asset_content_type: application/gzip
